<?php

namespace DogeDev\GoogleAuthenticator\Traits;

use DogeDev\GoogleAuthenticator\Exceptions\TwoFactorAuthenticationNotEnabled;
use DogeDev\GoogleAuthenticator\GoogleAuthenticatorFacade;
use GuzzleHttp\Client;

/**
 * Trait Verifies2FACode
 *
 * Generates a GoogleAuthenticator secret if the secret attribute is set during object creation.
 * Contains methods for outputting the QR code verifying the user submitted code (authorising action).
 *
 * @package App\Traits
 */
trait Verifies2FACode
{
    /**
     * Set the secret attribute.
     *
     * @return $this
     */
    public function enable2FA()
    {
        if (empty($this->secret)) {

            $this->secret = GoogleAuthenticatorFacade::createSecret();
            $this->save();
        }

        return $this;
    }

    /**
     * Get the two_factor_authentication_enabled attribute
     *
     * @return bool
     */
    public function getEnabled2faAttribute()
    {
        return !empty($this->secret);
    }

    /**
     * Returns a QR code for Google Authenticator
     *
     * @return string
     * @throws TwoFactorAuthenticationNotEnabled
     */
    public function getQRCodeURL()
    {
        if (empty($this->secret)) {

            throw new TwoFactorAuthenticationNotEnabled('2 Factor Authentication has not been enabled');
        }

        return GoogleAuthenticatorFacade::getQRCodeGoogleUrl($this->getNameForQRCode(), $this->secret);
    }

    /**
     * Gets the base64 encoded QR image
     *
     * @return string
     * @throws TwoFactorAuthenticationNotEnabled
     */
    public function getBase64EncodedQRImage()
    {
        $client = new Client();

        $response = $client->request('GET', $this->getQRCodeURL());

        $type = $response->getHeader('content-type')[0];

        $data = base64_encode($response->getBody());

        return "data:$type;base64,$data";
    }

    /**
     * Verifies the code generated by Google Authenticator
     *
     * @param null $code
     * @return bool
     * @throws TwoFactorAuthenticationNotEnabled
     */
    public function verifyCode($code = null)
    {
        if (!$this->secret) {

            throw new TwoFactorAuthenticationNotEnabled('2 Factor Authentication has not been enabled');
        }

        return GoogleAuthenticatorFacade::verifyCode($this->secret, $code, 0);
    }

    /**
     * Activates 2FA on the model
     *
     * @param null $code
     * @return boolean
     * @throws TwoFactorAuthenticationNotEnabled
     */
    public function activate2FA($code = null)
    {
        if (!$this->activated_2fa) {

            if (!$this->verifyCode($code)) {

                return false;
            }

            $this->activated_2fa = true;
            $this->save();
        }

        return true;
    }

    /**
     * Gets the name to be displayed in Google Authenticator
     *
     * @return string
     */
    public function getNameForQRCode()
    {
        return env('APP_NAME');
    }
}
